version: "0.2"
language: en,en-GB

import:
  - "${userHome}/.cspell.config.yaml"

dictionaryDefinitions:
  - name: project-words
    path: ./.cspell/project-words.txt
    addWords: true

dictionaries:
  - aws
  - project-words
  - terraform

useGitignore: true

ignorePaths:
  - "**/node_modules/**"
  - "**/dist/**"
